# Generated by Django 5.0.6 on 2024-06-15 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(max_length=80)),
                ('edad', models.IntegerField()),
                ('num_boleta', models.CharField(max_length=10)),
                ('promedio_general', models.FloatField()),
            ],
        ),
    ]
